show_downloads: true

theme: jekyll-theme-cayman

github:
  zip_url: https://github.com/01-Scripts/2Click-Iframe-Privacy/archive/master.zip
  tar_url: https://github.com/01-Scripts/2Click-Iframe-Privacy/archive/master.tar.gz
